namePrefix: ''
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

# imageの更新情報を記入し、Argo CDを起動させる
images:
  - name: image-registry.openshift-image-registry.svc:5000/tekton-practice/microapp-messenger-message-git
    newName: image-registry.openshift-image-registry.svc:5000/tekton-practice/microapp-messenger-message-git
    digest: sha256:8692cd9d7a21cb78e1deeff8a987c55eab6909af3d9fddf9d8b54972fd934b98
